### ISSUE TITLE
ConcurrentModificationException error java 11

### ISSUE THREAD

**Issue by dschnall** [OP-TED/eforms-core-java#9]
`java.util.ConcurrentModificationException
		at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1135)
		at eu.europa.ted.eforms.sdk.repository.SdkCodelistRepository.get(SdkCodelistRepository.java:54)
		at eu.europa.ted.eforms.sdk.repository.SdkCodelistRepository.get(SdkCodelistRepository.java:25)
		at eu.europa.ted.eforms.sdk.SdkSymbolResolver.getRootCodelistOfField(SdkSymbolResolver.java:162)
		at eu.europa.ted.efx.sdk1.EfxTemplateTranslatorV1.shorthandIndirectLabelReference(EfxTemplateTranslatorV1.java:315)
		at eu.europa.ted.efx.sdk1.EfxTemplateTranslatorV1.exitShorthandIndirectLabelReferenceFromContextField(EfxTemplateTranslatorV1.java:371)
		at eu.europa.ted.efx.sdk1.EfxParser$ShorthandIndirectLabelReferenceFromContextFieldContext.exitRule(EfxParser.java:873)
		at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:62)
		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:38)
		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
		at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
		at eu.europa.ted.efx.sdk1.EfxTemplateTranslatorV1.renderTemplate(EfxTemplateTranslatorV1.java:152)
		at eu.europa.ted.efx.sdk1.EfxTemplateTranslatorV1.renderTemplate(EfxTemplateTranslatorV1.java:132)
		at eu.europa.ted.efx.EfxTranslator.translateTemplate(EfxTranslator.java:105)
		at eu.europa.ted.eforms.viewer.NoticeViewer.buildXsl(NoticeViewer.java:309)
		at eu.europa.ted.eforms.viewer.NoticeViewer.generateHtml(NoticeViewer.java:92)`

**Comment by dschnall** [comment]
cannot reproduce anymore, was maybe mising saxon lib
